#!/bin/bash

# Copyright (C) 2010 David De Grave <david@ledav.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

P_VERSION="1.4.0"

function showHelp {
	cat <<-EOT
	MP3 Copier v$P_VERSION, (C) 2010 by David De Grave

	Read a mp3 list (path+file) from the standard input stream and copy
	each files to the specified directory under alphabetical, structured
	directories (<directory>/letter/author/mp3).

	The mp3 file names should follow the classic format: '<author> - <title>.mp3'

	Usage:
	 mp3cp [-hsv] [-{l|L}] [-j n] [-{m|M} name] <directory>

	Options:
	 -h       Show this help screen.
	 -v       Be more verbose.
	 -s       Continue in case of error.
	 -l       Don't copy files but hard link them (don't work with all filesystems).
	 -L       Same as -l but use symlinks instead.
	 -j n     Transfer 'n' files at the same time (0 = number of cpu threads).
	 -m name  Create a mp3 playlist file 'name' with the well copied items in <directory>.
	 -M name  Same as -m but add an entry even if the file already exist when copying.

	EOT
}

opt_cont=0
opt_link=0
opt_soft=0
opt_verb=0
opt_planyway=0
opt_maxsubproc=1
subproc=0

function check_args {
	while [ ${#} -gt 0 ]; do
		case $1 in
		 -h)	showHelp; exit 0;;
		 -v)    opt_verb=1;;
		 -l)	opt_link=1;;
		 -L)	opt_link=1; opt_soft=1;;
		 -s)	opt_cont=1;;
		 -j)    shift; opt_maxsubproc=$1;;
		 -M)	shift; playlist="$1"; opt_planyway=1;;
		 -m)	shift; playlist="$1";;
		 --)	shift; dest="$1";;
		esac
		shift
	done
}

check_args $(getopt -un "$0" -- "hvlLsj:M:m:" "$@") || exit

if [ -z "$dest" ]; then
        showHelp
        exit 0
fi
if ! [ -d "$dest" ]; then
	echo "$dest target directory doesn't exist !"
	exit 2
fi
if [ -n "$playlist" ]; then
	playlist="$dest/$playlist"
	echo "Creating playlist $playlist ..."
fi
if [ $opt_maxsubproc -eq 0 ]; then
	opt_maxsubproc=$(grep -ci ^proc /proc/cpuinfo)
fi
if [ $opt_link -eq 1 ]; then
	[ $opt_soft ] && link=s || link=l
fi

#set -x

while read line; do
	[ -f "$line" ] || continue

	bn=${line##*/}
	d=${bn%% - *}
	[ "$d" = "$bn" ] && d="Unknown"
	a=${d:0:1}
	a=${a^^}

	if ! [ -d "$dest/$a/$d" ] && ! mkdir -p "$dest/$a/$d"; then
		[ "$opt_cont" -eq 0 ] && exit 3
		continue
	fi

	if [ -e "$dest/$a/$d/$bn" ]; then 
		[ "$opt_verb" -eq 1 ] && echo "! File $dest/$a/$d/$bn already there. Skipped..."
		[ $opt_planyway -eq 1 ] && echo "$a/$d/$bn" >> "$playlist"
#		cp --attributes-only "$line" "$dest/$a/$d"
		continue
	fi

	(	if cp -v$link "$line" "$dest/$a/$d"; then
			[ -n "$playlist" ] && echo "$a/$d/$bn" >> "$playlist"
		else
			# Remove incomplete copied file
			rm -f "$dest/$a/$d/$bn"
			rmdir "$dest/$a/$d" &> /dev/null
			[ "$opt_cont" -eq 0 ] && exit 4
		fi
		exit 0
	) &

	# Use up to x subprocesses in parallel
	if (( ++subproc >= opt_maxsubproc )); then
		wait -n || exit $?
		let subproc--
	fi
done

wait
